const MemoryService = require('./MemoryService');
const { LLMClient } = require('../project/src/services/llmClient');

// 初始化记忆服务
const memoryService = new MemoryService();
memoryService.init();

// 初始化LLM客户端
const llmClient = new LLMClient({
  apiKey: 'your-api-key-here', // 替换为实际的API密钥
  model: 'gpt-3.5-turbo'
});

// 模拟聊天历史
const chatHistory = `
用户: 今天我学习了React的 useState hook，感觉理解了很多
助手: 很好啊！useState是React中最基础也最常用的hook之一
用户: 是的，我还做了一个小项目练习，感觉进步很大
助手: 太棒了！实践是最好的学习方式
用户: 明天我计划学习useEffect hook
助手: 好的，useEffect也很重要，它可以处理副作用
`;

// LLM生成函数
async function llmGenerate(prompt) {
  const response = await llmClient.completions({
    messages: [
      {
        role: 'system',
        content: '你是一个记忆管理助手，负责生成和提取记忆'
      },
      {
        role: 'user',
        content: prompt
      }
    ],
    temperature: 0.7,
    maxTokens: 1000
  });
  
  return response.choices[0].message?.content || '';
}

// 示例1: 自动生成每日记忆
async function exampleAutoGenerateDailyMemory() {
  console.log('=== 示例1: 自动生成每日记忆 ===');
  try {
    const dailyMemory = await memoryService.autoGenerateDailyMemory(chatHistory, llmGenerate);
    console.log('生成的每日记忆:');
    console.log(dailyMemory);
  } catch (error) {
    console.error('生成每日记忆失败:', error);
  }
}

// 示例2: 自动生成每周提炼
async function exampleAutoGenerateWeeklyRefinement() {
  console.log('\n=== 示例2: 自动生成每周提炼 ===');
  try {
    const weeklyRefinement = await memoryService.autoGenerateWeeklyRefinement(llmGenerate);
    console.log('生成的每周提炼:');
    console.log(weeklyRefinement);
  } catch (error) {
    console.error('生成每周提炼失败:', error);
  }
}

// 示例3: 提取相关记忆
async function exampleExtractRelevantMemories() {
  console.log('\n=== 示例3: 提取相关记忆 ===');
  try {
    const query = '我最近学习了什么？';
    const relevantMemories = await memoryService.extractRelevantMemories(query, llmGenerate);
    console.log('提取的相关记忆:');
    console.log(relevantMemories);
  } catch (error) {
    console.error('提取记忆失败:', error);
  }
}

// 示例4: 自动注入记忆到对话
async function exampleAutoInjectMemoryToConversation() {
  console.log('\n=== 示例4: 自动注入记忆到对话 ===');
  try {
    const query = '我明天计划做什么？';
    const conversationContext = await memoryService.autoInjectMemoryToConversation(query, llmGenerate);
    console.log('注入记忆后的对话上下文:');
    console.log(conversationContext);
  } catch (error) {
    console.error('注入记忆失败:', error);
  }
}

// 运行所有示例
async function runExamples() {
  await exampleAutoGenerateDailyMemory();
  await exampleAutoGenerateWeeklyRefinement();
  await exampleExtractRelevantMemories();
  await exampleAutoInjectMemoryToConversation();
}

runExamples();
