const path = require('path');
const Utils = require('./utils');
const config = require('./config');

/**
 * 记忆文件管理服务
 */
class MemoryService {
  /**
   * 构造函数
   */
  constructor() {
    this.memoryRoot = config.memoryRoot;
    this.dailyDir = config.dailyDir;
    this.weeklyDir = config.weeklyDir;
  }

  /**
   * 初始化服务
   */
  init() {
    // 确保根目录和子目录存在
    Utils.ensureDir(path.join(this.memoryRoot, this.dailyDir));
    Utils.ensureDir(path.join(this.memoryRoot, this.weeklyDir));
  }

  /**
   * 生成每日记忆文件名
   * @param {Date} date - 日期
   * @returns {string} 文件名
   */
  getDailyFileName(date = new Date()) {
    return `${Utils.formatDate(date)}.md`;
  }

  /**
   * 生成每周提炼文件名
   * @param {Date} date - 日期
   * @returns {string} 文件名
   */
  getWeeklyFileName(date = new Date()) {
    return `${Utils.formatWeek(date)}.md`;
  }

  /**
   * 读取每日记忆
   * @param {Date} date - 日期
   * @returns {string} 记忆内容
   */
  readDailyMemory(date = new Date()) {
    const fileName = this.getDailyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.dailyDir, fileName);
    return Utils.readFile(filePath);
  }

  /**
   * 写入每日记忆
   * @param {string} content - 记忆内容
   * @param {Date} date - 日期
   */
  writeDailyMemory(content, date = new Date()) {
    const fileName = this.getDailyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.dailyDir, fileName);
    Utils.writeFile(filePath, content);
  }

  /**
   * 读取每周提炼
   * @param {Date} date - 日期
   * @returns {string} 提炼内容
   */
  readWeeklyRefinement(date = new Date()) {
    const fileName = this.getWeeklyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.weeklyDir, fileName);
    return Utils.readFile(filePath);
  }

  /**
   * 写入每周提炼
   * @param {string} content - 提炼内容
   * @param {Date} date - 日期
   */
  writeWeeklyRefinement(content, date = new Date()) {
    const fileName = this.getWeeklyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.weeklyDir, fileName);
    Utils.writeFile(filePath, content);
  }

  /**
   * 获取所有每日记忆文件
   * @returns {string[]} 文件路径数组
   */
  getAllDailyMemories() {
    const dailyMemoriesDir = path.join(this.memoryRoot, this.dailyDir);
    return Utils.getFiles(dailyMemoriesDir);
  }

  /**
   * 获取所有每周提炼文件
   * @returns {string[]} 文件路径数组
   */
  getAllWeeklyRefinements() {
    const weeklyRefinementsDir = path.join(this.memoryRoot, this.weeklyDir);
    return Utils.getFiles(weeklyRefinementsDir);
  }

  /**
   * 删除每日记忆
   * @param {Date} date - 日期
   */
  deleteDailyMemory(date = new Date()) {
    const fileName = this.getDailyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.dailyDir, fileName);
    Utils.deleteFile(filePath);
  }

  /**
   * 删除每周提炼
   * @param {Date} date - 日期
   */
  deleteWeeklyRefinement(date = new Date()) {
    const fileName = this.getWeeklyFileName(date);
    const filePath = Utils.getFilePath(this.memoryRoot, this.weeklyDir, fileName);
    Utils.deleteFile(filePath);
  }

  /**
   * 生成每日记忆模板
   * @param {Date} date - 日期
   * @returns {string} 模板内容
   */
  generateDailyMemoryTemplate(date = new Date()) {
    const dateStr = Utils.formatDate(date);
    return `# ${dateStr} 每日记忆

## 今日要事

## 学习收获

## 工作进展

## 生活感悟

## 明日计划
`;
  }

  /**
   * 生成每周提炼模板
   * @param {Date} date - 日期
   * @returns {string} 模板内容
   */
  generateWeeklyRefinementTemplate(date = new Date()) {
    const weekStr = Utils.formatWeek(date);
    return `# ${weekStr} 每周提炼

## 本周总结

## 学习成果

## 工作成就

## 生活反思

## 下周计划
`;
  }

  /**
   * 创建并写入每日记忆模板
   * @param {Date} date - 日期
   */
  createDailyMemoryTemplate(date = new Date()) {
    const template = this.generateDailyMemoryTemplate(date);
    this.writeDailyMemory(template, date);
  }

  /**
   * 创建并写入每周提炼模板
   * @param {Date} date - 日期
   */
  createWeeklyRefinementTemplate(date = new Date()) {
    const template = this.generateWeeklyRefinementTemplate(date);
    this.writeWeeklyRefinement(template, date);
  }

  /**
   * 自动生成每日记忆
   * @param {string} chatHistory - 聊天历史
   * @param {Function} llmGenerate - LLM生成函数
   * @returns {Promise<string>} 生成的每日记忆内容
   */
  async autoGenerateDailyMemory(chatHistory, llmGenerate) {
    const today = new Date();
    const dateStr = Utils.formatDate(today);
    
    // 构建提示词
    const prompt = `# 每日记忆生成

请根据以下聊天历史，生成一份详细的每日记忆，包括今日要事、学习收获、工作进展、生活感悟和明日计划。

## 聊天历史
${chatHistory}

## 生成要求
- 内容要基于聊天历史，不要虚构信息
- 分类清晰，每个部分都要有具体内容
- 语言要自然流畅，符合日常记录风格
- 突出重点，忽略无关细节

## 输出格式
请严格按照以下格式输出：

# ${dateStr} 每日记忆

## 今日要事

## 学习收获

## 工作进展

## 生活感悟

## 明日计划
`;
    
    // 使用LLM生成每日记忆
    const generatedContent = await llmGenerate(prompt);
    
    // 写入每日记忆文件
    this.writeDailyMemory(generatedContent, today);
    
    return generatedContent;
  }

  /**
   * 自动生成每周提炼
   * @param {Function} llmGenerate - LLM生成函数
   * @returns {Promise<string>} 生成的每周提炼内容
   */
  async autoGenerateWeeklyRefinement(llmGenerate) {
    const today = new Date();
    const weekStr = Utils.formatWeek(today);
    
    // 获取本周的每日记忆
    const weekDailyMemories = this.getWeekDailyMemories(today);
    const dailyMemoriesContent = weekDailyMemories.map(memory => Utils.readFile(memory)).join('\n\n');
    
    // 构建提示词
    const prompt = `# 每周提炼生成

请根据以下本周的每日记忆，生成一份详细的每周提炼，包括本周总结、学习成果、工作成就、生活反思和下周计划。

## 本周每日记忆
${dailyMemoriesContent}

## 生成要求
- 内容要基于每日记忆，不要虚构信息
- 分类清晰，每个部分都要有具体内容
- 语言要自然流畅，符合总结风格
- 突出重点，忽略无关细节
- 对一周的内容进行整合和提炼，形成有价值的总结

## 输出格式
请严格按照以下格式输出：

# ${weekStr} 每周提炼

## 本周总结

## 学习成果

## 工作成就

## 生活反思

## 下周计划
`;
    
    // 使用LLM生成每周提炼
    const generatedContent = await llmGenerate(prompt);
    
    // 写入每周提炼文件
    this.writeWeeklyRefinement(generatedContent, today);
    
    return generatedContent;
  }

  /**
   * 获取本周的每日记忆文件
   * @param {Date} date - 日期
   * @returns {string[]} 本周每日记忆文件路径数组
   */
  getWeekDailyMemories(date = new Date()) {
    const dailyMemoriesDir = path.join(this.memoryRoot, this.dailyDir);
    const allDailyMemories = Utils.getFiles(dailyMemoriesDir);
    
    // 计算本周的开始和结束日期
    const weekStart = new Date(date);
    weekStart.setDate(date.getDate() - date.getDay() + 1); // 本周一
    weekStart.setHours(0, 0, 0, 0);
    
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekStart.getDate() + 6); // 本周日
    weekEnd.setHours(23, 59, 59, 999);
    
    // 筛选出本周的每日记忆
    return allDailyMemories.filter(filePath => {
      const fileName = path.basename(filePath);
      const dateStr = fileName.replace('.md', '');
      const memoryDate = new Date(dateStr);
      return memoryDate >= weekStart && memoryDate <= weekEnd;
    });
  }

  /**
   * 生成记忆提取Prompt
   * @param {string} query - 用户查询
   * @returns {string} 记忆提取Prompt
   */
  generateMemoryExtractionPrompt(query) {
    return `# 记忆提取

请从以下记忆库中提取与用户查询相关的信息，用于回答用户的问题。

## 用户查询
${query}

## 提取要求
- 只提取与查询相关的信息
- 保持信息的原始性，不要添加额外内容
- 提取的信息要准确、完整
- 如果没有相关信息，返回"无相关记忆"

## 记忆库
`;
  }

  /**
   * 提取相关记忆
   * @param {string} query - 用户查询
   * @param {Function} llmGenerate - LLM生成函数
   * @returns {Promise<string>} 提取的记忆内容
   */
  async extractRelevantMemories(query, llmGenerate) {
    // 获取所有记忆文件
    const allDailyMemories = this.getAllDailyMemories();
    const allWeeklyRefinements = this.getAllWeeklyRefinements();
    const allMemories = [...allDailyMemories, ...allWeeklyRefinements];
    
    // 读取所有记忆内容
    const memoriesContent = allMemories.map(filePath => {
      const content = Utils.readFile(filePath);
      const fileName = path.basename(filePath);
      return `## ${fileName}\n${content}`;
    }).join('\n\n');
    
    // 构建完整的提取Prompt
    const prompt = this.generateMemoryExtractionPrompt(query) + memoriesContent;
    
    // 使用LLM提取相关记忆
    const extractedMemories = await llmGenerate(prompt);
    
    return extractedMemories;
  }

  /**
   * 自动注入记忆到对话
   * @param {string} query - 用户查询
   * @param {Function} llmGenerate - LLM生成函数
   * @returns {Promise<string>} 注入记忆后的对话上下文
   */
  async autoInjectMemoryToConversation(query, llmGenerate) {
    // 提取相关记忆
    const relevantMemories = await this.extractRelevantMemories(query, llmGenerate);
    
    // 构建注入记忆后的对话上下文
    let conversationContext = '';
    
    if (relevantMemories && relevantMemories !== '无相关记忆') {
      conversationContext = `# 对话上下文

## 相关记忆
${relevantMemories}

## 用户当前查询
${query}
`;
    } else {
      conversationContext = `# 对话上下文

## 用户当前查询
${query}
`;
    }
    
    return conversationContext;
  }
}

module.exports = MemoryService;
